blueprint:
  name: "ZHA - IKEA Tradfri on/off switch - Custom Actions"
  description: Control anything using IKEA Tradfri on/off switch

  domain: automation

  input:
    remote:
      name: Switch
      description: IKEA Tradfri on/off switch to use
      selector:
        device:
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch

    button_on_short:
      name: ON button short press
      description: Action to run on press of On button
      default: []
      selector:
        action:
    button_off_short:
      name: OFF button short press
      description: Action to run on press of Off button
      default: []
      selector:
        action:
    button_on_long:
      name: ON button hold
      description: Action to run on hold of On button
      default: []
      selector:
        action:
    button_off_long:
      name: OFF button hold
      description: Action to run on hold of Off button
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
  - choose:
      - conditions:
          - "{{ command == 'on' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input button_on_short

      - conditions:
          - "{{ command == 'off' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input button_off_short

      - conditions:
          - "{{ command == 'move_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input button_on_long

      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input button_off_long
